# Python Workshop: Census and Trends

This notebook is ready to upload to [Google Colab](https://colab.research.google.com/). Before running the data-analysis sections, upload `census_and_trends_data.csv` using Colab's **Files** panel (folder icon on the left), then run the cells in order.

# Basics of Python

## What is Python?

Python is a programming language that can act like a calculator and can also
perform more complex data-analysis tasks. For this workshop, we will focus on
three general types: *numbers*, *strings*, and *variables*.


We use the **assignment operator** (`=`) to store information in variables. It
means "gets saved as."

In [2]:
# Numbers
6
20.5
13 + 30

# Strings
"waffles"
"Brigham Young University"

# Variables
my_favorite_number = 6
road_trip_snack = "waffles"

# Print our variables to see what is stored :) Print statements are a great tool to use when looking at your code
print(my_favorite_number)
print(road_trip_snack)

6
waffles

Python uses **functions** to manipulate and analyze data. Functions use
parentheses.

GoogleColab is great becuase it will send our last data point and print it below our code cell. Typically, we have to use `print()` statements to check values.

In [3]:
# Prints text in quotes
print("Hello, data explorer!")

# Takes the square root of a number
import math
math.sqrt(36)

Hello, data explorer!

6.0

## Key Concepts

The assignment operator (`=`) is different from the **comparison operator**
(`==`). A comparison returns either `True` or `False`.

In [4]:
# this will only tell us what the last one returns
# print statements are a fantastic way to show what your data is returning
5 == 5
"waffles" == "tacos"

False

**Libraries**, or **packages**, are toolboxes of functions written by other
people. This workshop uses the `pandas` package for data manipulation. If `pandas` is not installed, open your terminal in the bottom left side of the screen, and type: `pip install pandas`

In [5]:
# Load pandas in the current notebook/document
import pandas as pd

A **DataFrame** (used as df) is Python/pandas' word for a table or spreadsheet. Each row is
an observation, and each column is a variable. In this workshop, each row is a
U.S. state, with census-style facts and trend scores for food, sports, animals,
and hobbies.

If your data set does not read in, go to the **files** bar on the left side, and make sure you have uploaded the data set.

In [6]:
# Data from a CSV file gets saved as census_df
census_df = pd.read_csv("census_and_trends_data.csv")

In [7]:
# View the first five states (it's zero indexed)
census_df.head()

,state,has_nba_team,has_major_zoo,is_coastal,has_waffle_house,personality_profile,openness_rank,avg_temp_f,annual_sunny_days,ufo_sightings_per_100k,...,winemaking,sourdough baking,fermentation,canning,roasting coffee,mixology,barbecue smoking,yoga,pilates,meditation
0,Alabama,False,False,True,True,Friendly & Conventional,Moderate/Low,62.8,200,45.0,...,7,50,33,59,3,5,0,59,27,14
1,Alaska,False,False,True,False,Conventional & Duty-Bound,Moderate/Low,26.6,125,83.9,...,0,70,21,69,8,2,0,69,19,12
2,Arizona,True,False,False,False,Conventional & Duty-Bound,Moderate/Low,60.3,299,45.0,...,6,51,43,43,7,7,0,61,27,12
3,Arkansas,False,False,False,True,Conventional & Duty-Bound,Moderate/Low,60.4,200,45.0,...,0,52,28,66,2,4,0,63,25,12
4,California,True,True,True,False,Relaxed & Creative,High,59.4,265,38.5,...,13,41,57,31,8,4,0,60,28,12

Warning: Total number of columns (575) exceeds max_columns (20) limiting to first (20) columns.

# Census and Trends DataFrame Analysis

## Setup and Initialization

Run these lines before starting the analysis:

- import `pandas`
- read the census-and-trends CSV file
- view the table to make sure it loaded correctly

If you already did it above, there is no need to do it again.

In [8]:
# COMPLETED CODE BELOW
import pandas as pd

census_df = pd.read_csv("census_and_trends_data.csv")
census_df.head()  # You can also use census_df.columns or census_df.info()

,state,has_nba_team,has_major_zoo,is_coastal,has_waffle_house,personality_profile,openness_rank,avg_temp_f,annual_sunny_days,ufo_sightings_per_100k,...,winemaking,sourdough baking,fermentation,canning,roasting coffee,mixology,barbecue smoking,yoga,pilates,meditation
0,Alabama,False,False,True,True,Friendly & Conventional,Moderate/Low,62.8,200,45.0,...,7,50,33,59,3,5,0,59,27,14
1,Alaska,False,False,True,False,Conventional & Duty-Bound,Moderate/Low,26.6,125,83.9,...,0,70,21,69,8,2,0,69,19,12
2,Arizona,True,False,False,False,Conventional & Duty-Bound,Moderate/Low,60.3,299,45.0,...,6,51,43,43,7,7,0,61,27,12
3,Arkansas,False,False,False,True,Conventional & Duty-Bound,Moderate/Low,60.4,200,45.0,...,0,52,28,66,2,4,0,63,25,12
4,California,True,True,True,False,Relaxed & Creative,High,59.4,265,38.5,...,13,41,57,31,8,4,0,60,28,12

## Analyzing the Data

During this workshop, we will learn six common pandas operations:

- selecting columns with `[]`
- filtering rows with a Boolean condition
- creating columns with `.assign()`
- summarizing groups with `.groupby()` and `.agg()`
- previewing a DataFrame with `.info()`
- sorting rows with `.sort_values()`

By default Python will keep the ones that return `True` when analyzing the data.

### Selecting columns

Suppose you are planning a strange-but-fun road trip. Select a few useful
columns: the state name, climate, UFO sightings, waffle interest, and hiking
interest.

In [9]:
census_df[
    [
        "state",
        "avg_temp_f",
        "annual_sunny_days",
        "ufo_sightings_per_100k",
        "waffles",
        "hiking",
    ]
]

,state,avg_temp_f,annual_sunny_days,ufo_sightings_per_100k,waffles,hiking
0,Alabama,62.8,200,45.0,22,15
1,Alaska,26.6,125,83.9,26,14
2,Arizona,60.3,299,45.0,16,25
3,Arkansas,60.4,200,45.0,19,15
4,California,59.4,265,38.5,16,23
5,Colorado,45.1,245,45.0,12,22
6,Connecticut,49.0,200,45.0,13,24
7,Delaware,55.3,200,45.0,15,16
8,Florida,70.7,237,45.0,15,16
9,Georgia,63.5,200,45.0,21,21
10,Hawaii,70.0,200,45.0,19,23
11,Idaho,44.4,200,45.0,16,14
12,Illinois,51.8,200,45.0,13,22
13,Indiana,51.7,200,45.0,15,16
14,Iowa,47.8,200,45.0,14,15
15,Kansas,54.3,200,45.0,21,26
16,Kentucky,55.6,200,45.0,18,17
17,Louisiana,66.4,200,45.0,23,15
18,Maine,41.0,200,81.5,14,18
19,Maryland,54.2,200,45.0,17,22
20,Massachusetts,47.9,200,45.0,12,25
21,Michigan,44.4,170,45.0,15,17
22,Minnesota,41.2,200,45.0,15,14
23,Mississippi,63.4,200,45.0,25,14
24,Missouri,55.0,200,45.0,16,16
25,Montana,42.7,200,86.2,17,14
26,Nebraska,48.8,200,45.0,15,15
27,Nevada,49.9,252,45.0,26,25
28,New Hampshire,43.8,200,45.0,12,22
29,New Jersey,52.7,200,45.0,8,23
30,New Mexico,53.4,278,72.0,19,21
31,New York,45.4,160,45.0,10,26
32,North Carolina,59.0,200,45.0,19,18
33,North Dakota,40.4,200,45.0,18,10
34,Ohio,50.7,173,45.0,17,19
35,Oklahoma,59.6,200,45.0,18,15
36,Oregon,48.4,144,77.2,16,17
37,Pennsylvania,48.8,200,45.0,17,20
38,Rhode Island,50.1,200,45.0,14,20
39,South Carolina,62.4,200,45.0,21,14
40,South Dakota,45.2,200,45.0,19,12
41,Tennessee,57.6,200,45.0,19,19
42,Texas,64.8,235,22.1,21,18
43,Utah,48.6,200,45.0,16,22
44,Vermont,42.9,160,88.0,12,23
45,Virginia,55.1,200,45.0,18,22
46,Washington,48.3,152,88.3,19,20
47,West Virginia,51.8,200,45.0,21,13
48,Wisconsin,43.1,200,45.0,13,15
49,Wyoming,42.0,200,78.1,23,29

### Filtering rows

To see every state that has a Waffle House:

In [19]:
census_df[census_df["has_waffle_house"]]

,state,has_nba_team,has_major_zoo,is_coastal,has_waffle_house,personality_profile,openness_rank,avg_temp_f,annual_sunny_days,ufo_sightings_per_100k,...,winemaking,sourdough baking,fermentation,canning,roasting coffee,mixology,barbecue smoking,yoga,pilates,meditation
0,Alabama,False,False,True,True,Friendly & Conventional,Moderate/Low,62.8,200,45.0,...,7,50,33,59,3,5,0,59,27,14
3,Arkansas,False,False,False,True,Conventional & Duty-Bound,Moderate/Low,60.4,200,45.0,...,0,52,28,66,2,4,0,63,25,12
8,Florida,True,True,True,True,Friendly & Conventional,Moderate/Low,70.7,237,45.0,...,5,45,48,39,5,8,0,59,30,11
9,Georgia,True,True,True,True,Friendly & Conventional,Moderate/Low,63.5,200,45.0,...,8,42,43,47,4,6,0,61,26,13
12,Illinois,True,True,False,True,Conventional & Duty-Bound,Moderate/Low,51.8,200,45.0,...,7,42,38,53,4,5,0,63,24,13
13,Indiana,True,False,False,True,Conventional & Duty-Bound,Moderate/Low,51.7,200,45.0,...,6,49,26,68,2,4,0,63,25,12
16,Kentucky,False,False,False,True,Conventional & Duty-Bound,Moderate/Low,55.6,200,45.0,...,5,52,23,72,2,3,0,60,26,14
17,Louisiana,True,False,True,True,Conventional & Duty-Bound,Moderate/Low,66.4,200,45.0,...,6,38,40,48,5,7,0,59,27,14
19,Maryland,False,False,True,True,Conventional & Duty-Bound,Moderate/Low,54.2,200,45.0,...,7,36,45,44,4,7,0,60,26,14
23,Mississippi,False,False,True,True,Conventional & Duty-Bound,Moderate/Low,63.4,200,45.0,...,6,43,34,59,2,5,0,60,26,14
24,Missouri,False,True,False,True,Friendly & Conventional,Moderate/Low,55.0,200,45.0,...,6,53,27,66,3,4,0,64,24,12
32,North Carolina,True,True,True,True,Conventional & Duty-Bound,Moderate/Low,59.0,200,45.0,...,5,47,36,56,3,5,0,63,25,12
34,Ohio,True,True,False,True,Conventional & Duty-Bound,Moderate/Low,50.7,173,45.0,...,5,52,31,63,2,4,0,62,24,14
35,Oklahoma,True,False,False,True,Friendly & Conventional,Moderate/Low,59.6,200,45.0,...,5,53,36,56,3,5,0,64,24,12
37,Pennsylvania,True,True,False,True,Friendly & Conventional,Moderate/Low,48.8,200,45.0,...,6,46,33,61,3,3,0,64,23,13
39,South Carolina,False,False,True,True,Conventional & Duty-Bound,Moderate/Low,62.4,200,45.0,...,6,49,36,54,4,6,0,59,28,13
41,Tennessee,True,False,False,True,Friendly & Conventional,Moderate/Low,57.6,200,45.0,...,6,49,28,64,3,5,0,59,28,13
42,Texas,True,True,True,True,Friendly & Conventional,Moderate/Low,64.8,235,22.1,...,6,43,49,40,4,7,0,56,33,11
45,Virginia,False,False,True,True,Conventional & Duty-Bound,Moderate/Low,55.1,200,45.0,...,7,45,41,49,4,6,0,63,24,13

### Creating columns

The dataset includes trend scores for waffles, pancakes, and donuts. Create a
simple `Brunch_score` by adding them together. This will add a column at the end of your table.

In [11]:
census_df.assign(
    Brunch_score=(
        census_df["waffles"]
        + census_df["pancakes"]
        + census_df["donuts"]
    )
)

,state,has_nba_team,has_major_zoo,is_coastal,has_waffle_house,personality_profile,openness_rank,avg_temp_f,annual_sunny_days,ufo_sightings_per_100k,...,sourdough baking,fermentation,canning,roasting coffee,mixology,barbecue smoking,yoga,pilates,meditation,Brunch_score
0,Alabama,False,False,True,True,Friendly & Conventional,Moderate/Low,62.8,200,45.0,...,50,33,59,3,5,0,59,27,14,87
1,Alaska,False,False,True,False,Conventional & Duty-Bound,Moderate/Low,26.6,125,83.9,...,70,21,69,8,2,0,69,19,12,87
2,Arizona,True,False,False,False,Conventional & Duty-Bound,Moderate/Low,60.3,299,45.0,...,51,43,43,7,7,0,61,27,12,69
3,Arkansas,False,False,False,True,Conventional & Duty-Bound,Moderate/Low,60.4,200,45.0,...,52,28,66,2,4,0,63,25,12,89
4,California,True,True,True,False,Relaxed & Creative,High,59.4,265,38.5,...,41,57,31,8,4,0,60,28,12,67
5,Colorado,True,True,False,False,Relaxed & Creative,High,45.1,245,45.0,...,52,41,49,4,6,0,65,22,13,63
6,Connecticut,False,False,True,False,Friendly & Conventional,Moderate/Low,49.0,200,45.0,...,45,40,46,4,10,0,61,26,13,69
7,Delaware,False,False,True,False,Conventional & Duty-Bound,Moderate/Low,55.3,200,45.0,...,50,40,49,5,6,0,63,24,13,70
8,Florida,True,True,True,True,Friendly & Conventional,Moderate/Low,70.7,237,45.0,...,45,48,39,5,8,0,59,30,11,71
9,Georgia,True,True,True,True,Friendly & Conventional,Moderate/Low,63.5,200,45.0,...,42,43,47,4,6,0,61,26,13,82
10,Hawaii,False,False,True,False,Conventional & Duty-Bound,Moderate/Low,70.0,200,45.0,...,50,53,33,8,6,0,70,21,9,87
11,Idaho,False,False,False,False,Conventional & Duty-Bound,Moderate/Low,44.4,200,45.0,...,61,25,68,4,3,0,66,23,11,74
12,Illinois,True,True,False,True,Conventional & Duty-Bound,Moderate/Low,51.8,200,45.0,...,42,38,53,4,5,0,63,24,13,76
13,Indiana,True,False,False,True,Conventional & Duty-Bound,Moderate/Low,51.7,200,45.0,...,49,26,68,2,4,0,63,25,12,81
14,Iowa,False,False,False,False,Friendly & Conventional,Moderate/Low,47.8,200,45.0,...,54,24,71,2,3,0,65,22,13,72
15,Kansas,False,False,False,False,Friendly & Conventional,Moderate/Low,54.3,200,45.0,...,43,45,46,5,4,0,66,14,20,88
16,Kentucky,False,False,False,True,Conventional & Duty-Bound,Moderate/Low,55.6,200,45.0,...,52,23,72,2,3,0,60,26,14,85
17,Louisiana,True,False,True,True,Conventional & Duty-Bound,Moderate/Low,66.4,200,45.0,...,38,40,48,5,7,0,59,27,14,92
18,Maine,False,False,True,False,Friendly & Conventional,Moderate/Low,41.0,200,81.5,...,61,23,71,2,4,0,68,20,12,81
19,Maryland,False,False,True,True,Conventional & Duty-Bound,Moderate/Low,54.2,200,45.0,...,36,45,44,4,7,0,60,26,14,72
20,Massachusetts,True,False,True,False,Friendly & Conventional,High,47.9,200,45.0,...,44,48,42,4,6,0,67,20,13,73
21,Michigan,True,False,False,False,Conventional & Duty-Bound,Moderate/Low,44.4,170,45.0,...,51,25,68,3,4,0,64,23,13,72
22,Minnesota,True,False,False,False,Conventional & Duty-Bound,Moderate/Low,41.2,200,45.0,...,54,23,72,2,3,0,64,22,14,74
23,Mississippi,False,False,True,True,Conventional & Duty-Bound,Moderate/Low,63.4,200,45.0,...,43,34,59,2,5,0,60,26,14,99
24,Missouri,False,True,False,True,Friendly & Conventional,Moderate/Low,55.0,200,45.0,...,53,27,66,3,4,0,64,24,12,79
25,Montana,False,False,False,False,Conventional & Duty-Bound,Moderate/Low,42.7,200,86.2,...,68,23,70,5,2,0,70,19,11,73
26,Nebraska,False,True,False,False,Friendly & Conventional,Moderate/Low,48.8,200,45.0,...,54,32,63,2,3,0,65,24,11,68
27,Nevada,False,False,False,False,Relaxed & Creative,Moderate/Low,49.9,252,45.0,...,46,44,36,12,8,0,59,28,13,75
28,New Hampshire,False,False,True,False,Friendly & Conventional,Moderate/Low,43.8,200,45.0,...,54,28,63,5,4,0,69,19,12,82
29,New Jersey,False,False,True,False,Friendly & Conventional,Moderate/Low,52.7,200,45.0,...,42,49,33,5,13,0,60,29,11,55
30,New Mexico,False,False,False,False,Relaxed & Creative,Moderate/Low,53.4,278,72.0,...,47,40,52,3,5,0,65,22,13,75
31,New York,True,True,True,False,Friendly & Conventional,High,45.4,160,45.0,...,32,42,42,5,11,0,63,25,12,60
32,North Carolina,True,True,True,True,Conventional & Duty-Bound,Moderate/Low,59.0,200,45.0,...,47,36,56,3,5,0,63,25,12,75
33,North Dakota,False,False,False,False,Conventional & Duty-Bound,Moderate/Low,40.4,200,45.0,...,70,24,72,1,3,0,66,22,12,87
34,Ohio,True,True,False,True,Conventional & Duty-Bound,Moderate/Low,50.7,173,45.0,...,52,31,63,2,4,0,62,24,14,78
35,Oklahoma,True,False,False,True,Friendly & Conventional,Moderate/Low,59.6,200,45.0,...,53,36,56,3,5,0,64,24,12,87
36,Oregon,True,False,True,False,Relaxed & Creative,High,48.4,144,77.2,...,52,28,65,4,3,0,67,19,14,76
37,Pennsylvania,True,True,False,True,Friendly & Conventional,Moderate/Low,48.8,200,45.0,...,46,33,61,3,3,0,64,23,13,73
38,Rhode Island,False,False,True,False,Friendly & Conventional,Moderate/Low,50.1,200,45.0,...,51,40,50,3,7,0,67,22,11,77
39,South Carolina,False,False,True,True,Conventional & Duty-Bound,Moderate/Low,62.4,200,45.0,...,49,36,54,4,6,0,59,28,13,77
40,South Dakota,False,False,False,False,Conventional & Duty-Bound,Moderate/Low,45.2,200,45.0,...,74,22,72,3,3,0,61,25,14,79
41,Tennessee,True,False,False,True,Friendly & Conventional,Moderate/Low,57.6,200,45.0,...,49,28,64,3,5,0,59,28,13,81
42,Texas,True,True,True,True,Friendly & Conventional,Moderate/Low,64.8,235,22.1,...,43,49,40,4,7,0,56,33,11,79
43,Utah,True,False,False,False,Relaxed & Creative,Moderate/Low,48.6,200,45.0,...,49,35,55,5,5,0,62,25,13,73
44,Vermont,False,False,False,False,Friendly & Conventional,Moderate/Low,42.9,160,88.0,...,55,28,68,2,2,0,69,16,15,71
45,Virginia,False,False,True,True,Conventional & Duty-Bound,Moderate/Low,55.1,200,45.0,...,45,41,49,4,6,0,63,24,13,75
46,Washington,False,True,True,False,Relaxed & Creative,High,48.3,152,88.3,...,53,34,58,5,3,0,64,22,14,75
47,West Virginia,False,False,False,False,Conventional & Duty-Bound,Moderate/Low,51.8,200,45.0,...,58,20,75,3,2,0,66,19,15,87
48,Wisconsin,True,False,False,False,Conventional & Duty-Bound,Moderate/Low,43.1,200,45.0,...,55,20,75,2,3,0,68,19,13,70
49,Wyoming,False,False,False,False,Conventional & Duty-Bound,Moderate/Low,42.0,200,78.1,...,54,54,34,7,5,0,73,12,15,74

Warning: Total number of columns (576) exceeds max_columns (20) limiting to first (20) columns.

`.assign()` returns a new DataFrame. It does not overwrite `census_df` unless
you save the result back into a variable.

### Summarizing groups

The states are grouped into personality profiles. Find the average temperature,
average annual sunshine, average UFO sightings, and number of states in each
profile. The command `.agg` is how you can apply one or more aggregate functions like `mean` and `sum` to the data.

In [12]:
census_df.groupby("personality_profile", as_index=False).agg(
    average_temperature_f=("avg_temp_f", "mean"),
    average_sunny_days=("annual_sunny_days", "mean"),
    average_ufo_sightings=("ufo_sightings_per_100k", "mean"),
    number_of_states=("state", "size"),
)

,personality_profile,average_temperature_f,average_sunny_days,average_ufo_sightings,number_of_states
0,Conventional & Duty-Bound,51.587500,198.625000,49.716667,24
1,Friendly & Conventional,52.973684,199.578947,47.978947,19
2,Relaxed & Creative,50.442857,219.428571,58.714286,7

Use `.groupby()` to split rows into groups before calculating a summary. For
example, find the average UFO-sighting rate for each personality profile:

In [13]:
(
    census_df.groupby("personality_profile", as_index=False)
    .agg(average_ufo_sightings=("ufo_sightings_per_100k", "mean"))
)

         personality_profile  average_ufo_sightings
0  Conventional & Duty-Bound              49.716667
1    Friendly & Conventional              47.978947
2         Relaxed & Creative              58.714286

NOTE: Keep in mind that seeing personality profile against the average UFO_sighting does not mean that you can conclude Relaxed and Creative personalities are more likely to see a UFO. There may be other factors that we have not considered, so it is important to do more tests to find other variables that could connect the data.

### Inspecting, grouping, and sorting data

Use `.info()` to quickly inspect a DataFrame. This compact form is useful for
a very wide dataset like this one below. `verbose` it how you decide what type of summary you want. When `verbose=False` that tells the system we want a concise version of our information. When `verbose=True` we will have number of columns, names, data, number of values per column (not including null), and how much memory is used. Try changing `verbose` to `True` and see how the data changes.

In [23]:
census_df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Columns: 575 entries, state to meditation
dtypes: bool(4), float64(10), int64(557), object(4)
memory usage: 223.4+ KB

Use `.sort_values()` to order rows by a column. `ascending=False` tells the code that we want most to least sunny. `head` lets us choose how many data points we want represented. Here are the ten sunniest
states, from most to least sunny:

In [15]:
(
    census_df.sort_values("annual_sunny_days", ascending=False)
    [["state", "annual_sunny_days"]]
    .head(10)
)

         state  annual_sunny_days
2      Arizona                299
30  New Mexico                278
4   California                265
27      Nevada                252
5     Colorado                245
8      Florida                237
42       Texas                235
3     Arkansas                200
10      Hawaii                200
0      Alabama                200

Consider what would happen if you took the top 30 sunniest states. How would we choose between states with the same amount of sunny days?


That is enough to begin exploring the data!

## Practice Time

**Filtering:** Find states with at least 250 sunny days per year. These might
be good candidates for a sunny road trip.

Find the row for Utah. Hint: Use the `==` operator.

**Creating columns:** Use the 'assign' function to create a `Brunch_score` column that adds the trend scores
for waffles, pancakes, and donuts. When adding scores, do something like `census_df["column_name"] + census_df["column_name"]`.

Create a Boolean `UFO_hotspot` column that is `True` when a state has at least
60 UFO sightings per 100,000 people.

**Selecting:** Create a smaller DataFrame with a state's personality profile,
capybara trend score, and Dungeons & Dragons trend score.

Now select only the state names.

**Summarizing:** Find the total population represented in the dataset.

np.int64(334235923)

Find the coldest average temperature in the dataset.

Which state has that temperature the minimum temperature?
Hint: you will need to use `loc` which locates a specific column, and `.idxmin` which returns the label of the minimum, and save it as a variable. Then show the data.

# Extra Information and Challenges

## More Comparison Operators

The following operators each return `True` or `False`:

- `!=` checks inequality
- `>` checks whether the left value is greater
- `<` checks whether the left value is less
- `>=` checks whether the left value is greater than or equal
- `<=` checks whether the left value is less than or equal

Notice that Colab only displays the last value.

In [16]:
"hiking" != "skiing"
51 > 15
1000 < 1000
41 >= 41.5
50 <= 300

True

For example, find states with at least three national parks:

Show only states that are not coastal. Hint: use the ~ before your usual call to signify that we want the census_df that is not coastal.

Try other comparisons. For example, find states where the capybara trend score
is greater than 40, or states without a major zoo.

## Combining pandas Operations

You can combine filtering, selecting, creating columns, and grouping. For
example, find the average pizza and hiking trend scores for states with an NBA
team, grouped by personality profile.

Among states with a Waffle House, find the state with the largest waffle trend
score.

For coastal states, select their state name, personality profile, annual sunny
days, and craft breweries per 100,000 people.

Create an `Outdoor_adventure` column that is `True` when a state has at least
20 hiking-trend points and at least one national park. Then count outdoor
adventure states in each personality profile.