# Python Workshop: Census and Trends

This notebook is ready to upload to [Google Colab](https://colab.research.google.com/). Before running the data-analysis sections, upload `census_and_trends_data.csv` using Colab's **Files** panel (folder icon on the left), then run the cells in order.

# Basics of Python

## What is Python?

Python is a programming language that can act like a calculator and can also
perform more complex data-analysis tasks. For this workshop, we will focus on
three general types: *numbers*, *strings*, and *variables*.


We use the **assignment operator** (`=`) to store information in variables. It
means "gets saved as."

In [ ]:
# Numbers
6
20.5
13 + 30

# Strings
"waffles"
"Brigham Young University"

# Variables
my_favorite_number = 6
road_trip_snack = "waffles"

# Print our variables to see what is stored :) Print statements are a great tool to use when looking at your code
print(my_favorite_number)
print(road_trip_snack)

6
waffles

Python uses **functions** to manipulate and analyze data. Functions use
parentheses.

GoogleColab is great becuase it will send our last data point and print it below our code cell. Typically, we have to use `print()` statements to check values.

In [ ]:
# Prints text in quotes
print("Hello, data explorer!")

# Takes the square root of a number
import math
math.sqrt(36)

Hello, data explorer!

6.0

## Key Concepts

The assignment operator (`=`) is different from the **comparison operator**
(`==`). A comparison returns either `True` or `False`.

In [ ]:
# this will only tell us what the last one returns
# print statements are a fantastic way to show what your data is returning
5 == 5
"waffles" == "tacos"

False

**Libraries**, or **packages**, are toolboxes of functions written by other
people. This workshop uses the `pandas` package for data manipulation. If `pandas` is not installed, open your terminal in the bottom left side of the screen, and type: `pip install pandas`

In [ ]:
# Load pandas in the current notebook/document
import pandas as pd

A **DataFrame** (used as df) is Python/pandas' word for a table or spreadsheet. Each row is
an observation, and each column is a variable. In this workshop, each row is a
U.S. state, with census-style facts and trend scores for food, sports, animals,
and hobbies.

If your data set does not read in, go to the **files** bar on the left side, and make sure you have uploaded the data set.

In [ ]:
# Data from a CSV file gets saved as census_df
census_df = pd.read_csv("census_and_trends_data_2026-10-7.csv")

In [ ]:
# View the first five states (it's zero indexed)
census_df.head()

,state,has_nba_team,has_major_zoo,is_coastal,has_waffle_house,personality_profile,openness_rank,avg_temp_f,annual_sunny_days,ufo_sightings_per_100k,...,singing,djing,magic tricks,sourdough baking,fermentation,canning,barbecue smoking,yoga,pilates,meditation
0,Alabama,False,False,True,True,Friendly & Conventional,Low,62.8,213,39.8,...,51,24,51,34,15,39,81,12,36,14
1,Alaska,False,False,True,False,Relaxed & Creative,Low,26.6,125,83.9,...,35,31,54,78,17,84,0,17,27,14
2,Arizona,True,False,False,False,Relaxed & Creative,Moderate,60.3,299,62.5,...,40,41,54,46,15,23,47,19,52,18
3,Arkansas,False,False,False,True,Friendly & Conventional,Low,60.4,218,44.8,...,43,28,52,38,15,58,0,12,31,11
4,California,True,True,True,False,Relaxed & Creative,High,59.4,265,38.5,...,39,53,55,37,25,24,46,22,61,24

# Census and Trends DataFrame Analysis

## Setup and Initialization

Run these lines before starting the analysis:

- import `pandas`
- read the census-and-trends CSV file
- view the table to make sure it loaded correctly

If you already did it above, there is no need to do it again.

In [2]:
# COMPLETED CODE BELOW
import pandas as pd

census_df = pd.read_csv("census_and_trends_data_2026-10-7.csv")
census_df.head()  # You can also use census_df.columns or census_df.info()

,state,has_nba_team,has_major_zoo,is_coastal,has_waffle_house,personality_profile,openness_rank,avg_temp_f,annual_sunny_days,ufo_sightings_per_100k,...,singing,djing,magic tricks,sourdough baking,fermentation,canning,barbecue smoking,yoga,pilates,meditation
0,Alabama,False,False,True,True,Friendly & Conventional,Low,62.8,213,39.8,...,51,24,51,34,15,39,81,12,36,14
1,Alaska,False,False,True,False,Relaxed & Creative,Low,26.6,125,83.9,...,35,31,54,78,17,84,0,17,27,14
2,Arizona,True,False,False,False,Relaxed & Creative,Moderate,60.3,299,62.5,...,40,41,54,46,15,23,47,19,52,18
3,Arkansas,False,False,False,True,Friendly & Conventional,Low,60.4,218,44.8,...,43,28,52,38,15,58,0,12,31,11
4,California,True,True,True,False,Relaxed & Creative,High,59.4,265,38.5,...,39,53,55,37,25,24,46,22,61,24

## Analyzing the Data

During this workshop, we will learn six common pandas operations:

- selecting columns with `[]`
- filtering rows with a Boolean condition
- creating columns with `.assign()`
- summarizing groups with `.groupby()` and `.agg()`
- previewing a DataFrame with `.info()`
- sorting rows with `.sort_values()`

By default Python will keep the ones that return `True` when analyzing the data.

### Selecting columns

Suppose you are planning a strange-but-fun road trip. Select a few useful
columns: the state name, climate, UFO sightings, waffle interest, and hiking
interest.

In [ ]:
census_df[
    [
        "state",
        "avg_temp_f",
        "annual_sunny_days",
        "ufo_sightings_per_100k",
        "waffles",
        "hiking",
    ]
]

,state,avg_temp_f,annual_sunny_days,ufo_sightings_per_100k,waffles,hiking
0,Alabama,62.8,213,39.8,52,14
1,Alaska,26.6,125,83.9,70,28
2,Arizona,60.3,299,62.5,51,22
3,Arkansas,60.4,218,44.8,40,14
4,California,59.4,265,38.5,49,22
5,Colorado,45.1,245,67.2,42,28
6,Connecticut,49.0,204,48.9,55,18
7,Delaware,55.3,201,41.5,43,13
8,Florida,70.7,237,29.8,47,14
9,Georgia,63.5,218,33.5,59,16
10,Hawaii,70.0,240,54.2,52,23
11,Idaho,44.4,206,69.8,46,20
12,Illinois,51.8,189,32.1,50,15
13,Indiana,51.7,186,42.5,40,13
14,Iowa,47.8,205,46.2,33,14
15,Kansas,54.3,230,44.1,57,34
16,Kentucky,55.6,189,43.5,38,16
17,Louisiana,66.4,216,28.4,44,13
18,Maine,41.0,192,81.5,43,25
19,Maryland,54.2,202,34.9,56,15
20,Massachusetts,47.9,201,41.9,42,19
21,Michigan,44.4,170,41.2,43,15
22,Minnesota,41.2,198,40.5,40,19
23,Mississippi,63.4,218,27.2,42,11
24,Missouri,55.0,206,47.5,43,15
25,Montana,42.7,205,86.2,41,28
26,Nebraska,48.8,223,43.1,36,12
27,Nevada,49.9,252,68.4,67,20
28,New Hampshire,43.8,198,71.5,39,25
29,New Jersey,52.7,206,36.2,45,15
30,New Mexico,53.4,278,72.0,47,19
31,New York,45.4,160,30.5,47,20
32,North Carolina,59.0,213,40.8,60,17
33,North Dakota,40.4,201,45.0,35,11
34,Ohio,50.7,173,38.9,45,15
35,Oklahoma,59.6,234,42.8,38,13
36,Oregon,48.4,144,77.2,44,23
37,Pennsylvania,48.8,179,39.2,55,17
38,Rhode Island,50.1,201,45.9,43,16
39,South Carolina,62.4,216,45.2,62,14
40,South Dakota,45.2,213,46.0,41,14
41,Tennessee,57.6,207,37.9,54,18
42,Texas,64.8,235,22.1,53,15
43,Utah,48.6,238,53.1,50,26
44,Vermont,42.9,160,88.0,42,28
45,Virginia,55.1,205,35.8,52,18
46,Washington,48.3,152,88.3,54,24
47,West Virginia,51.8,164,58.3,38,15
48,Wisconsin,43.1,188,46.8,40,18
49,Wyoming,42.0,222,78.1,100,100

### Filtering rows

To see every state that has a Waffle House:

In [ ]:
census_df[census_df["has_waffle_house"]]

,state,has_nba_team,has_major_zoo,is_coastal,has_waffle_house,personality_profile,openness_rank,avg_temp_f,annual_sunny_days,ufo_sightings_per_100k,...,singing,djing,magic tricks,sourdough baking,fermentation,canning,barbecue smoking,yoga,pilates,meditation
0,Alabama,False,False,True,True,Friendly & Conventional,Low,62.8,213,39.8,...,51,24,51,34,15,39,81,12,36,14
3,Arkansas,False,False,False,True,Friendly & Conventional,Low,60.4,218,44.8,...,43,28,52,38,15,58,0,12,31,11
8,Florida,True,True,True,True,Friendly & Conventional,Moderate,70.7,237,29.8,...,39,45,50,34,17,22,34,18,61,19
9,Georgia,True,True,True,True,Friendly & Conventional,Moderate,63.5,218,33.5,...,38,40,52,30,17,31,45,18,46,17
12,Illinois,True,True,False,True,Conventional & Duty-Bound,Moderate,51.8,189,32.1,...,38,51,58,35,16,38,31,18,44,17
13,Indiana,True,False,False,True,Friendly & Conventional,Low,51.7,186,42.5,...,39,33,58,37,14,61,0,13,31,12
16,Kentucky,False,False,False,True,Friendly & Conventional,Low,55.6,189,43.5,...,46,25,54,36,14,85,76,13,33,15
17,Louisiana,True,False,True,True,Friendly & Conventional,Low,66.4,216,28.4,...,41,47,50,27,14,28,0,14,35,17
19,Maryland,False,False,True,True,Conventional & Duty-Bound,Moderate,54.2,202,34.9,...,38,51,86,31,16,28,35,17,49,20
23,Mississippi,False,False,True,True,Friendly & Conventional,Low,63.4,218,27.2,...,100,24,44,24,16,46,0,11,33,12
24,Missouri,False,True,False,True,Friendly & Conventional,Low,55.0,206,47.5,...,42,29,63,48,16,65,100,14,33,14
32,North Carolina,True,True,True,True,Friendly & Conventional,Moderate,59.0,213,40.8,...,42,41,57,38,17,42,36,18,43,17
34,Ohio,True,True,False,True,Friendly & Conventional,Low,50.7,173,38.9,...,41,33,57,42,17,58,0,15,36,17
35,Oklahoma,True,False,False,True,Friendly & Conventional,Low,59.6,234,42.8,...,43,28,55,42,16,41,0,12,26,12
37,Pennsylvania,True,True,False,True,Conventional & Duty-Bound,Moderate,48.8,179,39.2,...,41,44,58,40,20,57,29,17,39,19
39,South Carolina,False,False,True,True,Friendly & Conventional,Low,62.4,216,45.2,...,44,36,53,37,15,39,66,15,42,15
41,Tennessee,True,False,False,True,Friendly & Conventional,Low,57.6,207,37.9,...,44,28,58,38,15,60,74,14,42,15
42,Texas,True,True,True,True,Friendly & Conventional,Moderate,64.8,235,22.1,...,35,35,49,27,16,22,57,15,52,15
45,Virginia,False,False,True,True,Conventional & Duty-Bound,Moderate,55.1,205,35.8,...,40,46,56,39,19,41,41,18,40,19

### Creating columns

The dataset includes trend scores for waffles, pancakes, and donuts. Create a
simple `Brunch_score` by adding them together. This will add a column at the end of your table.

In [6]:
census_df = census_df.assign(
    Brunch_score=(
        census_df["waffles"]
        + census_df["pancakes"]
        + census_df["donuts"]
    )
)

census_df.sort_values("Brunch_score", ascending=False)[
    [
        "state",
        "Brunch_score",
    ]
]

             state  Brunch_score
49         Wyoming           234
6      Connecticut           200
28   New Hampshire           199
38    Rhode Island           198
18           Maine           193
20   Massachusetts           187
12        Illinois           187
15          Kansas           184
37    Pennsylvania           178
19        Maryland           178
29      New Jersey           177
39  South Carolina           175
32  North Carolina           175
44         Vermont           173
27          Nevada           170
31        New York           170
10          Hawaii           168
1           Alaska           167
43            Utah           166
41       Tennessee           165
9          Georgia           164
34            Ohio           163
45        Virginia           161
2          Arizona           161
13         Indiana           158
7         Delaware           158
11           Idaho           155
21        Michigan           155
8          Florida           155
46      Washington           151
3         Arkansas           150
4       California           150
48       Wisconsin           149
36          Oregon           148
24        Missouri           147
42           Texas           146
0          Alabama           145
5         Colorado           143
16        Kentucky           143
35        Oklahoma           143
17       Louisiana           142
30      New Mexico           141
22       Minnesota           138
23     Mississippi           134
47   West Virginia           130
40    South Dakota           127
14            Iowa           124
26        Nebraska           124
25         Montana           122
33    North Dakota           118

`.assign()` returns a new DataFrame. It does not overwrite `census_df` unless
you save the result back into a variable.

### Summarizing groups

The states are grouped into personality profiles. Find the average temperature,
average annual sunshine, average UFO sightings, and number of states in each
profile. The command `.agg` is how you can apply one or more aggregate functions like `mean` and `sum` to the data.

In [8]:
census_df.groupby("personality_profile", as_index=False).agg(
    average_temperature_f=("avg_temp_f", "mean"),
    average_sunny_days=("annual_sunny_days", "mean"),
    average_ufo_sightings=("ufo_sightings_per_100k", "mean"),
    number_of_states=("state", "size"),
)

,personality_profile,average_temperature_f,average_sunny_days,average_ufo_sightings,number_of_states
0,Conventional & Duty-Bound,48.742857,190.571429,47.792857,14
1,Friendly & Conventional,55.486957,208.739130,40.639130,23
2,Relaxed & Creative,49.161538,220.846154,69.184615,13

Use `.groupby()` to split rows into groups before calculating a summary. For
example, find the average UFO-sighting rate for each personality profile:

In [9]:
(
    census_df.groupby("personality_profile", as_index=False)
    .agg(average_ufo_sightings=("ufo_sightings_per_100k", "mean"))
)

         personality_profile  average_ufo_sightings
0  Conventional & Duty-Bound              47.792857
1    Friendly & Conventional              40.639130
2         Relaxed & Creative              69.184615

NOTE: Keep in mind that seeing personality profile against the average UFO_sighting does not mean that you can conclude Relaxed and Creative personalities are more likely to see a UFO. There may be other factors that we have not considered, so it is important to do more tests to find other variables that could connect the data.

### Inspecting, grouping, and sorting data

Use `.info()` to quickly inspect a DataFrame. This compact form is useful for
a very wide dataset like this one below. `verbose` it how you decide what type of summary you want. When `verbose=False` that tells the system we want a concise version of our information. When `verbose=True` we will have number of columns, names, data, number of values per column (not including null), and how much memory is used. Try changing `verbose` to `True` and see how the data changes.

In [10]:
census_df.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Columns: 559 entries, state to Brunch_score
dtypes: bool(4), float64(9), int64(542), object(4)
memory usage: 217.1+ KB

Use `.sort_values()` to order rows by a column. `ascending=False` tells the code that we want most to least sunny. `head` lets us choose how many data points we want represented. Here are the ten sunniest
states, from most to least sunny:

In [ ]:
(
    census_df.sort_values("annual_sunny_days", ascending=False)
    [["state", "annual_sunny_days"]]
    .head(10)
)

         state  annual_sunny_days
2      Arizona                299
30  New Mexico                278
4   California                265
27      Nevada                252
5     Colorado                245
10      Hawaii                240
43        Utah                238
8      Florida                237
42       Texas                235
35    Oklahoma                234

Consider what would happen if you took the top 30 sunniest states. How would we choose between states with the same amount of sunny days?


That is enough to begin exploring the data!

## Practice Time

**Filtering:** Find states with at least 250 sunny days per year. These might
be good candidates for a sunny road trip.

Find the row for Utah. Hint: Use the `==` operator.

**Creating columns:** Use the 'assign' function to create a `Brunch_score` column that adds the trend scores
for kolaches, bagels, and beignets. When adding scores, do something like `census_df["column_name"] + census_df["column_name"]`.

Create a Boolean `UFO_hotspot` column that is `True` when a state has at least
60 UFO sightings per 100,000 people.

**Selecting:** Create a smaller DataFrame with a state's personality profile,
capybara trend score, and Dungeons & Dragons trend score.

Now select only the state names.

**Summarizing:** Find the total population represented in the dataset.

Find the coldest average temperature in the dataset.

Which state has that temperature the minimum temperature?
Hint: you will need to use `loc` which locates a specific column, and `.idxmin` which returns the label of the minimum, and save it as a variable. Then show the data.

# Extra Information and Challenges

## More Comparison Operators

The following operators each return `True` or `False`:

- `!=` checks inequality
- `>` checks whether the left value is greater
- `<` checks whether the left value is less
- `>=` checks whether the left value is greater than or equal
- `<=` checks whether the left value is less than or equal

Notice that Colab only displays the last value.

In [ ]:
"hiking" != "skiing"
51 > 15
1000 < 1000
41 >= 41.5
50 <= 300

True

For example, find states with at least three national parks:

Show only states that are not coastal. Hint: use the ~ before your usual call to signify that we want the census_df that is not coastal.

Try other comparisons. For example, find states where the capybara trend score
is greater than 40, or states without a major zoo.

## Combining pandas Operations

You can combine filtering, selecting, creating columns, and grouping. For
example, find the average pizza and hiking trend scores for states with an NBA
team, grouped by personality profile.

Among states with a Waffle House, find the state with the largest waffle trend
score.

For coastal states, select their state name, personality profile, annual sunny
days, and U.F.O. sightings per 100,000 people.

Create an `Outdoor_adventure` column that is `True` when a state has at least
20 hiking-trend points and at least one national park. Then count outdoor
adventure states in each personality profile.